// <auto-generated />
namespace GeneralStore.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class modifiedProduct : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modifiedProduct));
        
        string IMigrationMetadata.Id
        {
            get { return "202203132234160_modifiedProduct"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
